language: android
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
    - android-sdk-license-.+

before_install:
    - yes | sdkmanager "platforms;android-28"

script:
    - ./gradlew assembleRelease --stacktrace